words:
  - choco
  - coassb
  - cython
  - dmypy
  - gomod
  - ipynb
  - jzsj
  - kczy
  - kjflb
  - kjflid
  - kjxxb
  - kssj
  - liblaf
  - mdurl
  - mkdocs
  - nointeraction
  - nuitka
  - pybuilder
  - pycache
  - pydantic
  - pyflow
  - pyinstaller
  - pynr
  - pypa
  - pypackages
  - pysj
  - pytype
  - queryxnxq
  - scsj
  - sfgk
  - thauth
  - tqdm
  - typer
  - wjdx
  - wjid
  - wjlx
  - wlkc
  - wlkcid
  - wlxt
  - xktjb
  - xszyid
  - yjwg
  - ywkcm
  - zyid
  - zywkcm
ignorePaths:
  - "*-lock.*"
  - "*.lock"
dictionaries:
  - bash
  - cpp
  - cpp-refined
  - dotnet
  - golang
  - makefile
  - npm
  - python
  - python-common
allowCompoundWords: true
